### ISSUE TITLE
Referencia bibliografica de su contenido

### ISSUE THREAD

**Issue by thecircleoflifefree** [josedom24/curso_python3#1]
Segun la licencia CC-BY-SA debo reconocer su autoria adecuadamente antes de referenciarlo en alguna documentacion, por ende quisiera saber de antemano si tiene alguna preferencia en particular para la elaboracion de la r**eferencia bibliografica** del material posteado en su pagina web, en especifico https://www.josedomingo.org/pledin/2012/01/introduccion-a-django-creacion-de-una-aplicacion-crud/ , o si unicamente me rijo bajo el standard de APA version 6 para referenciar dicho link. Si bien el estandar cumple con este objetivo, hay autores que prefieren que se evidencia la referencia bibliografica de una forma en particular. Al no encontrar dicha informacion en su pagina web, me remito humildemente por este medio para respetar su guia.

Gracias.

**Comment by josedom24** [comment]
Gracias por contactar. 

No hace falta que lo referencias de una manera particular, puedes hacerlo como quieras.

Un saludo
